apiVersion: v1
kind: Service
metadata:
  name: mgcloud-frontend
  labels:
    app: mgcloud-frontend


spec:
  type: NodePort
  selector: 
    app: mgcloud-ft
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173